function(ros2_shm_target_dependencies target)
  set(scope PUBLIC)

  foreach(dependency IN LISTS ARGN)
    if(dependency STREQUAL "INTERFACE" OR dependency STREQUAL "PUBLIC" OR dependency STREQUAL "PRIVATE")
      set(scope "${dependency}")
      continue()
    endif()

    if(TARGET "${dependency}::${dependency}")
      if(scope STREQUAL "INTERFACE")
        target_link_libraries("${target}" INTERFACE "${dependency}::${dependency}")
      else()
        target_link_libraries("${target}" "${dependency}::${dependency}")
      endif()
    elseif(DEFINED ${dependency}_TARGETS)
      if(scope STREQUAL "INTERFACE")
        target_link_libraries("${target}" INTERFACE ${${dependency}_TARGETS})
      else()
        target_link_libraries("${target}" ${${dependency}_TARGETS})
      endif()
    else()
      target_include_directories("${target}" ${scope} ${${dependency}_INCLUDE_DIRS})
      if(scope STREQUAL "INTERFACE")
        target_link_libraries("${target}" INTERFACE ${${dependency}_LIBRARIES})
      else()
        target_link_libraries("${target}" ${${dependency}_LIBRARIES})
      endif()
      target_compile_definitions("${target}" ${scope} ${${dependency}_DEFINITIONS})
    endif()
  endforeach()
endfunction()
